### ISSUE TITLE
Need way to login if lose access to auth phone or email

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#398] opened 2022-08-03 18:16 UTC
We need a way for participants to change their login information if they originally logged in and authenticated with a phone number or an email address that they no longer can access.

**Comment by Davinkjohnson** [comment] 2023-07-03 17:40
Closing this as it's now a duplicate of the now implemented "login switch mechanism" in both the PWA and SMDB.

**Closed by Davinkjohnson** 2023-07-03 17:40 UTC
Labels: general functionality, PWA
